import type { Metadata } from "next";
import "./globals.css";
import { VagancieProvider } from "./providers/Vagancie";
import { ControlerProvider } from "./providers/HeaderControler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <ControlerProvider>
        <VagancieProvider>
          {children}
          </VagancieProvider>
        </ControlerProvider>
      </body>
    </html>
  );
}
